---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
script: bundle exec rake test
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_GEM_VERSION="3.4.3"
  - PUPPET_GEM_VERSION="3.5.1" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="3.6.2" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="3.7.1" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="3.7.1" STRICT_VARIABLES=yes FUTURE_PARSER=yes

matrix:
  fast_finish: true

notifications:
  email: false
